name: infra
on:
    workflow_dispatch:
        inputs:
            terraform_job:
                type: choice
                description: Terraform
                options:
                    - plan
                    - apply
                    - destroy
permissions:
    contents: read
    id-token: write
jobs:
    terraform:
        name: "Terraform"
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                shell: bash
                working-directory: ".atmos-tf/components/terraform/"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::069363837566:role/github-tnote-terraform
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: ap-southeast-2

            - name: Generate vars.tfvars
              run: |
                  cat > "./vars.tfvars" <<EOF
                    db_pass = "${{ secrets.db_pass }}"
                  EOF

                  cat ./vars.tfvars
            - name: Terraform init
              run: terraform init

            - name: Terraform plan
              run: terraform plan -var-file=vars.tfvars -input=false

            - name: Terraform apply
              if: ${{ inputs.terraform_job == 'apply'}}
              run: terraform apply -var-file=vars.tfvars -input=false -auto-approve

            - name: Terraform destroy
              if: ${{ inputs.terraform_job == 'destroy'}}
              run: terraform destroy -var-file=vars.tfvars -input=false -auto-approve
