name: network
on: 
    workflow_dispatch:

permissions:
    contents: read
    id-token: write
jobs:
    terraform:
        name: 'Terraform'
        runs-on: ubuntu-latest
        environment: production

        